### ISSUE TITLE
Bitboards should use tuples rather than lists

### ISSUE THREAD

**Issue by oscardssmith** [alemelis/Bobby.jl#28]
This should be a pure performance win.

**Comment by alemelis** [comment]
thanks for the hint

are you referring to the moves list (or arrays in general)?
https://github.com/alemelis/Bobby.jl/blob/2e1e8b27bd0a6c007c14ed681b73d868e1e1627e/src/structs.jl#L52-L54

**Comment by oscardssmith** [comment]
No. I meant things like lines 1-10 of king.jl (and for all the other magics). This matters because tuples are immutable, so lots more optimizations become valid by default.

**Comment by alemelis** [comment]
this is a good point

indeed I guess it would be beneficial to add some benchmarks to the repo so that all these improvements can be tracked

(by the way, PRs are welcomed 🙂  )
